### ISSUE TITLE
Can't seem to run benchmarks from a clone

### ISSUE THREAD

**Issue by kezabelle** [clarkduvall/serpy#10]
Docs say do this:
```
$ git clone https://github.com/clarkduvall/serpy.git && cd serpy
$ tox -e benchmarks
```
So:
```
$ mktmpenv --python=`which python3`
$ python -V
Python 3.4.3
$ git clone https://github.com/clarkduvall/serpy.git && cd serpy
$ pip install -r requirements.txt   # this line is missing from the docs btw
$ tox -e benchmarks
GLOB sdist-make: /path/tmp-64a1638fe69a816/serpy/setup.py
benchmarks create: /path/tmp-64a1638fe69a816/serpy/.tox/benchmarks
benchmarks installdeps: Django==1.7.7, djangorestframework==3.1.1, marshmallow==1.2.4
benchmarks inst: /path/tmp-64a1638fe69a816/serpy/.tox/dist/serpy-0.1.0.zip
...
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/path/pip-ipr7v027-build/setup.py", line 4, in <module>
        import serpy
      File "/path/pip-ipr7v027-build/serpy/__init__.py", line 1, in <module>
        from serpy.fields import (
      File "/path/pip-ipr7v027-build/serpy/fields.py", line 1, in <module>
        import six
    ImportError: No module named 'six'
```

Seems like maybe the `deps` for `testenv` aren't being carried across to `testenv:benchmarks` and nor is the `install_requires` from the `setup.py` being picked up?

Other `tox -e` invocations work fine.

**Comment by clarkduvall** [comment]
@kezabelle can you try again, should work now. Ended up just adding six to the deps for benchmarks.
